apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: micro-srv-saas-01
build:
  local:
    push: false
  artifacts:
    - image: arrigolupori/micro-srv-saas-01-courses
      context: courses
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
